### ISSUE TITLE
Add OpenSearch schema

### ISSUE THREAD

**Issue by rmmh** [TruthfulTechnology/unicode.party#31]
This will allow Chrome and other browsers to automatically register these in the toolbar, letting you do things like `uni<tab>heart<enter>` => `http://unicode.party/?query=heart`.

**Comment by bmispelon** [comment]
From what I can see, there's already an opensearch schema referenced in the header (it was added in 408230f08a51cb0bff9bc84a4fcda045f50cd8d5).

I was able to add the search using my browser (firefox) so it seems to be working.

**Comment by treyhunner** [comment]
There is an open search schema, but I'm not sure why it doesn't work automatically. I thought Chrome user to know to search a website automatically when I hit the "Tab" key if it had an open search schema, but it seems not.

If there is some way to make the search schema automatically detected and used, I'd love that.

**Comment by bmispelon** [comment]
I haven't been able to find a lot of documentation on how the Chrome "Tab" search works, but the [MDN documentation on opensearch](https://developer.mozilla.org/en-US/docs/Web/OpenSearch#troubleshooting_tips) has some useful troubleshooting tips, and in particular:

> Your server should serve OpenSearch plugins using Content-Type: application/opensearchdescription+xml.

Looking at `curl -D- https://unicode.party/opensearch.xml`, it seems the content type served is `application/xml`. I'm not sure if there's a way to change that easily.

**Comment by treyhunner** [comment]
@bmispelon I just customized the `Content-Type` header for it but I don't think it fixed it.

It looks Chrome used to [aut-add site search engines](https://superuser.com/questions/276069/google-chrome-automatically-adding-websites-to-my-list-of-search-engines) and then [disabled this feature](https://superuser.com/questions/1396554/how-to-enable-google-chrome-automatically-adding-websites-to-my-list-of-search-e), which explains why I've noticed site search hasn't been acting the way I expect the last couple years on various websites I visit.

I confirmed this fact by starting a new Chrome profile and visiting a few websites with search, including unicode.party, and seeing that the search was found but it wasn't auto-added to Chrome:

![image](https://user-images.githubusercontent.com/285352/173241054-afc4e26c-4ff8-448f-aa7d-f1bf85d1bac2.png)

I accidentally closed this issue in #42 but I think we may need to close this as "can't fix", since we've done all we can to tell the browser that this is a searchable site.

I suppose the one thing we could add is some instructions to tell the user "here's how you get unicode.party search enabled in your URL bar".

**Comment by bmispelon** [comment]
Oh that's too bad, I was hoping that changing the header would fix it 😞 

During my searches I've found some mentions that Chrome might require the user to make an initial search on the site before it offers the "tab search" functionality.
I'm not sure how reliable that information is, but if that's true then it could be an explanation here. Since the search is done 100% client-side, no request is made and that might not trigger Chrome's "initial request" detection.

Personally I've stopped using custom search engines for my browser and instead use DuckDuckGo's "bangs" (like `!unicodeparty`) to achieve a similar functionality. I'm not sure I even know how to add a custom opensearch-backed engine in my browser anymore.

**Comment by treyhunner** [comment]
> During my searches I've found some mentions that Chrome might require the user to make an initial search on the site before it offers the "tab search" functionality. I'm not sure how reliable that information is, but if that's true then it could be an explanation here. Since the search is done 100% client-side, no request is made and that might not trigger Chrome's "initial request" detection.

I tried searching on Wikipedia and StackOverflow and those didn't seem to add themselves automatically either.

I suspect that this change may have been deliberate, either in response to users disliking auto-site search or because Google realized it decreased their ad revenue due to fewer Google searches.

> Personally I've stopped using custom search engines for my browser and instead use DuckDuckGo's "bangs" (like `!unicodeparty`) to achieve a similar functionality. I'm not sure I even know how to add a custom opensearch-backed engine in my browser anymore.

I had no idea that `!unicodeparty` worked on DuckDuckGo 😮

**Comment by bmispelon** [comment]
> I had no idea that `!unicodeparty` worked on DuckDuckGo open_mouth

I suggested it to them way back in 2016 and they added it almost right away. It's probably in my top 5 most used but I have no idea if others actually use it too 😅
